name: Linux build

on: [push, pull_request, workflow_dispatch]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache CMake Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ${{runner.workspace}}/build/_deps
          ${{runner.workspace}}/_deps
        key: linux-cmake-deps-${{ hashFiles('CMakeLists.txt') }}

    - name: Install Dependencies
      run: | 
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev

    
    - name: Configure CMake

      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_TESTING="OFF" -DisStatic=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
