name: Linux/Mac Release build

on:
  push:
    tags:
      - 'v*.*.*'

env:
  BUILD_TYPE: Release

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache build dependencies
      uses: actions/cache@v3
      with:
        path: build/
        key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-build-deps-

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install Dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev

    - name: Install Dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install freeglut

    - name: Install Dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install freeglut
        choco install mesa
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_TESTING="OFF" -DisStatic=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: CPack
      run: cd build && cpack

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{github.workspace}}/build/Platformer*
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
