name: Linux build

on: [push, pull_request, workflow_dispatch]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache build dependencies
      uses: actions/cache@v2
      with:
        path: build/_deps
        key: ${{ runner.os }}-build-deps-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-build-deps-

    - name: Set up CMake
      uses: lukka/get-cmake@latest  
      with:
        useLocalCache: true
        useCloudCache: false

    - name: Install Dependencies
      run: | 
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev

    
    - name: Configure CMake

      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_TESTING="OFF" -DisStatic=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # - name: CPack
    #   run: cpack --verbose
