name: Linux build

on:
  push:
    tags:
      - 'v*.*.*'

env:
  BUILD_TYPE: Release

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install Dependencies
      run: | 
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev

    
    - name: Configure CMake

      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_TESTING="OFF" -DisStatic=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: CPack
      run: cd build && cpack

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{github.workspace}}/build/Platformer*
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
